# Generated by Django 5.0.14 on 2026-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='collection_posters/'),
        ),
    ]
