# Generated by Django 5.0.14 on 2026-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_collection_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_universe',
            field=models.BooleanField(default=False),
        ),
    ]
