# Generated by Django 5.0.14 on 2026-09-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MediaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], default='movie', max_length=10)),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('poster_local', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_anime', models.BooleanField(default=False)),
                ('my_status', models.CharField(choices=[('plan_to_watch', 'Планирую'), ('watching', 'Смотрю'), ('dropped', 'Бросил'), ('completed', 'Просмотрено')], default='plan_to_watch', max_length=20)),
                ('download_status', models.CharField(choices=[('none', 'Нет'), ('need_download', 'Нужно скачать'), ('downloaded', 'Скачано')], default='none', max_length=20)),
                ('my_rating', models.IntegerField(blank=True, null=True)),
                ('movie_length', models.IntegerField(blank=True, null=True)),
                ('is_series', models.BooleanField(default=False)),
                ('total_series_length', models.IntegerField(blank=True, null=True)),
                ('series_length', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('external_kp_id', models.CharField(blank=True, default='', max_length=50)),
                ('external_imdb_id', models.CharField(blank=True, default='', max_length=50)),
                ('external_tmdb_id', models.CharField(blank=True, default='', max_length=50)),
                ('external_shikimori_id', models.CharField(blank=True, default='', max_length=50)),
                ('rating_kp', models.FloatField(blank=True, null=True)),
                ('rating_imdb', models.FloatField(blank=True, null=True)),
                ('rating_tmdb', models.FloatField(blank=True, null=True)),
                ('rating_shikimori', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, to='media.country')),
                ('genres', models.ManyToManyField(blank=True, to='media.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('plan_to_watch', 'Планирую'), ('watching', 'Смотрю'), ('dropped', 'Бросил'), ('completed', 'Просмотрено')], default='', max_length=20)),
                ('new_status', models.CharField(choices=[('plan_to_watch', 'Планирую'), ('watching', 'Смотрю'), ('dropped', 'Бросил'), ('completed', 'Просмотрено')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='media.mediaentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media histories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaInformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informers', to='media.mediaentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
