# Generated by Django 5.0.14 on 2026-10-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('shelves', '0003_collection_is_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaentry',
            name='universe_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universe_media', to='shelves.collection'),
        ),
    ]
